# -*- coding: utf-8 -*-
"""python fundamentals

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13uPcJmoU0JlWN2xQl0iN_PEqb2AQlmu1
"""

# =======================================================
# CODOMAX DIGITAL - DAY 1 TO DAY 4 TASK
# Python & Data Science Fundamentals - High Priority
# Name: Sineka | Beginner Level
# =======================================================

print("="*50)
print("DAY 1: SETUP & BASICS")
print("="*50)
# Install Python and set up Google Colab - Done!
print("Python setup completed in Google Colab")
print("Hello Codomax Digital! Starting Data Science Journey...\n")

# -------------------------------------------------------
print("="*50)
print("DAY 2: VARIABLES, LISTS, DICTIONARIES")
print("="*50)

# 1. VARIABLES
intern_name = "Sineka"
intern_id = "CODOMAX_DS_01"
age = 21
is_completed_day1 = True
python_version = 3.11

print(f"Name: {intern_name}")
print(f"ID: {intern_id}")
print(f"Python Version: {python_version}")

# 2. LISTS - Data Science ku collection store panna
skills_to_learn = ["Python", "Variables", "Loops", "Functions", "Lists", "Dictionaries", "File Handling"]
learning_days = [1, 2, 3, 4]
print(f"\nSkills List: {skills_to_learn}")
print(f"First Skill: {skills_to_learn[0]}")
print(f"Last Skill: {skills_to_learn[-1]}")

# List operations
skills_to_learn.append("Pandas")
print(f"After adding Pandas: {skills_to_learn}")

# 3. DICTIONARIES - Real world data maathiri (key:value)
student_profile = {
    "name": "Sineka",
    "company": "Codomax Digital",
    "domain": "Python & Data Science",
    "duration": "Day 1 - Day 4",
    "priority": "High",
    "level": "Beginner"
}

print("\nMy Internship Profile:")
for key, value in student_profile.items():
    print(f" {key} : {value}")

# -------------------------------------------------------
print("\n" + "="*50)
print("DAY 3: LOOPS, FUNCTIONS, FILE HANDLING")
print("="*50)

# 4. LOOPS
print("\n--- For Loop Example ---")
print("What I will do:")
for i, task in enumerate(skills_to_learn, 1):
    print(f"{i}. {task}")

print("\n--- While Loop Example ---")
day = 1
while day <= 4:
    print(f"Day {day} - Learning in Progress...")
    day += 1
print("Day 1-4 Task Completed!")

# 5. FUNCTIONS
print("\n--- Functions Example ---")

def welcome_message(name):
    return f"Welcome {name} to Codomax Digital Internship!"

def calculate_progress(completed_days, total_days=4):
    percentage = (completed_days / total_days) * 100
    return percentage

def check_task_status(skill_name):
    # Function with if-else
    if skill_name in skills_to_learn:
        return f"{skill_name} - COMPLETED"
    else:
        return f"{skill_name} - PENDING"

print(welcome_message(intern_name))
print(f"My Progress: {calculate_progress(4)}%")

for skill in ["Python", "Loops", "Machine Learning"]:
    print(check_task_status(skill))

# 6. FILE HANDLING
print("\n--- File Handling Example ---")

# Writing file
with open("Codomax_Task_Report.txt", "w") as file:
    file.write("CODOMAX DIGITAL - TASK REPORT\n")
    file.write("=============================\n")
    file.write(f"Name: {intern_name}\n")
    file.write(f"Task: Python & Data Science Fundamentals\n")
    file.write(f"Days: Day 1 - Day 4\n")
    file.write(f"Topics Covered:\n")
    for topic in skills_to_learn:
        file.write(f"- {topic}\n")
    file.write("\nStatus: Successfully Completed\n")

print("Report file created: Codomax_Task_Report.txt")

# Reading file
print("\nReading the report file:")
with open("Codomax_Task_Report.txt", "r") as file:
    content = file.read()
    print(content)

# -------------------------------------------------------
print("="*50)
print("DAY 4: DATA SCIENCE CONCEPTS & REAL-WORLD")
print("="*50)

print("""
What is Data Science?

Data Science is combination of Python + Statistics + Data Analysis
to extract useful insights from data.

Real-World Applications:
1. E-commerce (Amazon, Flipkart): Product Recommendation
2. OTT (Netflix, YouTube): Video Recommendation
3. Healthcare: Disease Prediction using data
4. Banking: Fraud Detection
5. Transport: Ola/Uber - Price & Time Prediction
6. Social Media: Instagram/Facebook - Feed Personalization

Basic Data Science Workflow:
Data Collection -> Data Cleaning -> Data Analysis -> Visualization -> Prediction
""")

# Simple Data Science Demo using Dictionary as Data
print("--- Simple Data Science Demo ---")
try:
    import pandas as pd

    # Creating sample dataset
    data = {
        "Day": ["Day 1", "Day 2", "Day 3", "Day 4"],
        "Topic": ["Setup & Python Basics", "Lists & Dicts", "Loops & Functions", "File Handling & DS Concepts"],
        "Status": ["Completed", "Completed", "Completed", "Completed"],
        "Hours_Spent": [2, 3, 3, 2]
    }

    df = pd.DataFrame(data)
    print(df)
    print(f"\nTotal Hours Spent: {df['Hours_Spent'].sum()} hours")
    print(f"Task Completion: 100%")

except ImportError:
    print("Pandas not installed, but concepts covered!")

print("\n" + "="*50)
print("FINAL STATUS: DAY 1 TO DAY 4 - TASK 100% COMPLETED")
print("Ready to submit to Codomax Digital Dashboard")
print("="*50)